---
title: "Project3b-MTH"
author: "John Roeder"
date: "2024-04-23"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyverse)
library(tidyr)
library(leaps)
youtube <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-02/youtube.csv')
head(youtube)
youtube$popular<- with(youtube,ifelse(view_count>200000,1,0))

```



```{r}
# preprocessing 
num_columns <- ncol(youtube)
print(paste("Total Columns: ", num_columns))

#get col names 
#also check for nans
columns =colnames(youtube)
print(columns)
nas <- colSums(is.na(youtube))

#find cols w nans
cols_w_nas <- names(nas[nas > 0])
print("cols w Nans")
print(cols_w_nas)

#get the total missing for each col and print
missing_counts <- colSums(is.na(youtube))
print(missing_counts)



```



```{r}

#for numeric cols w emptys
numeric_cols <- c("like_count", "dislike_count", "favorite_count", "comment_count", "view_count")
for (col in numeric_cols) {
  median_value <- median(youtube[[col]], na.rm = TRUE)  
  youtube[[col]][is.na(youtube[[col]])] <- median_value 
}

youtube <- youtube[!is.na(youtube$published_at), ]

head(data)

#check again to see if fixes worked. 
missing_counts <- colSums(is.na(youtube))
print(missing_counts)

```



